apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "quay.io/nsthompson/wwt-demo-app:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: HEADER_COLOR
              value: {{ .Values.env.headerColor }}
            - name: HEADER_TITLE
              value: {{ .Values.env.headerTitle }}
          # Uncomment if you want readiness probes.
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #     scheme: HTTP
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
