{{ if and ( eq .Values.deploymentTarget "kubernetes") ( eq .Values.deploymentIngress.type "nginx" ) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.deploymentIngress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.service.targetPort }}
        path: /
        pathType: Prefix
{{ end }}