{{ if eq .Values.deploymentTarget "openshift" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  slack_api_url: <slack_api_url>
  bigpanda_url: <bigpanda_url>
  bigpanda_token: <bigpanda_token>
{{ end }}