# Namespace / Openshift Project
namespace: wwt-demo

replicaCount: 1

# deploymentTarget can be kubernetes or openshift
deploymentTarget: openshift
# used when deploymentTarget is kubernetes
deploymentIngress:
  type: nginx
  host: kubernetes.docker.internal
# used when deploymentTarget is openshift
openshiftCluster:
  ingressDomain: apps.observelab.rhhc.wwtatc.com

# Service Configuration
service:
  type: ClusterIP
  protocol: TCP
  port: 8080
  targetPort: 8080

# Environment Configuration
env:
  headerColor: blue
  headerTitle: WWT Demo Application
